version: '3'
services:
  activity-service: 
    build: ./ActivityService
    container_name: activity-service
    ports:
      - 8002:80

  mysql:
    image: mysql
    container_name: activity_database
    environment:
      MYSQL_ROOT_PASSWORD: super
      MYSQL_DATABASE: activity_db
    volumes:
      - ./mysql_db_data:/var/lib/mysql
      - ./entry:/docker-entrypoint-initdb.d/ 
